name: wordstock
description: A new Flutter project.



publish_to: 'none'

version: 2.0.1+2

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  sqflite: ^2.0.2+1
  path_provider: ^2.0.11
  io: ^1.0.3
  flutter_screenutil: ^5.8.4
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_serializable: ^6.2.0
  json_annotation: ^4.6.0
  flutter_slidable: ^2.0.0
  uuid: ^3.0.6
  flip_card: ^0.6.0
  swipe_cards: ^1.0.0
  flutter_native_splash: ^2.2.7
  path: ^1.8.1
  swipeable_stack: ^0.4.3
  swipable_stack: ^1.2.0
  google_fonts: ^5.1.0
  file: ^7.0.0
  carousel_slider: ^4.2.1
  percent_indicator: ^4.0.1
  gap: ^3.0.1
  analyzer: ^5.12.0


flutter_native_splash:
  image: "assets/images/splash.png"
  color: "#ffffff"
  fullscreen: true




dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  riverpod_generator: ^2.3.9






flutter_icons:
   android: true
   ios: true
   image_path: 'assets/images/iconand.png'
   adaptive_icon_background: '#ffffff'




flutter:
  uses-material-design: true




