# ワークフローの名前（任意）
name: front-github-actions
# mainブランチに対してPRが作成されたタイミングをトリガーとする
# つまり、どのタイミングでこのワークフローが走るかが「on:」では定義されています
on:
  push: #pushはトリガー
    branches: [develop] #ここで具体的なトリガーのタイミングを指示
  pull_request:
    branches: [develop]
    types: [opened, synchronize]

jobs:
  test_create_name:
    name: widget test for wordstock
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          #ref: ${{ github.event.pull_request.head.sha }}
          flutter-version: '3.13.4'
          channel: "stable"
          cache: true
      - name: Run flutter version
        run: flutter --version
      - name: Install packages
        run: flutter pub get
      - run: flutter analyze
        name: Test
      - run: flutter test