name: Post Release

on:
  pull_request:
    types:
      - 'closed'

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - name: create release with note
        run: |
          tag=v$(jq -r ".ios.version" ./version.json)
          gh release create $tag --generate-notes
