name: Submit

# どのようにワークフローを実行するかの定義
on:
  pull_request:
    types:
      - 'closed'

jobs:
  submit-ios:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release:ios')
    name: Install and build ios
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: macos-latest
    environment: production:ios
    steps:
      # リポジトリのチェックアウト
      - uses: actions/checkout@v3
      # Node.jsのセットアップ
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache-dependency-path: 'yarn.lock'
          cache: yarn
      # ExpoとEASのセットアップ
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: 3.15.0
          token: ${{ secrets.EXPO_TOKEN }}

      # 依存関係のインストール
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # ビルドファイルの生成と提出
      - name: Prod iOS Build on EAS
        run: eas build --profile prod:release --platform ios --auto-submit --non-interactive


      - run: |
          export RELEASE_CHANNEL=v$(jq -r ".ios.version" ./version.json)
          npx zx ./scripts/zx/notify_built.mjs
      - run: |
          export RELEASE_CHANNEL=v$(jq -r ".ios.version" ./version.json)
          npx zx ./scripts/zx/notify_built.mjs

  submit-android:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release:android')
    name: Install and build android
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: macos-latest
    environment: production:android
    steps:
      # リポジトリのチェックアウト
      - uses: actions/checkout@v3
      # Node.jsのセットアップ
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache-dependency-path: 'yarn.lock'
          cache: yarn
      # ExpoとEASのセットアップ
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: 3.15.0
          token: ${{ secrets.EXPO_TOKEN }}
      # 依存関係のインストール
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      # ビルドファイルの生成と提出
      - name: Prod Android Build on EAS
        run: eas build --profile prod:release --platform android --auto-submit --non-interactive
      # Slackへの通知
      - run: |
          export RELEASE_CHANNEL=v$(jq -r ".android.version" ./version.json)
          npx zx ./scripts/zx/notify_built.mjs
      - run: |
          export RELEASE_CHANNEL=v$(jq -r ".android.version" ./version.json)
          npx zx ./scripts/zx/notify_built.mjs